/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectohilos;

import javax.swing.ImageIcon;

/**
 *
 * @author Chumy
 */
public class Incendio extends javax.swing.JFrame {
    String icono;
    ImageIcon imagen;
    Thread hiloF= new Thread(objIncendio);
    static HiloIncendio objIncendio= new HiloIncendio();
    boolean estadoF= false;
    
    
    public Incendio() {
        
        this.setSize(720,576);
        
        initComponents();
        this.setLocationRelativeTo(null);
        hiloF.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFuego = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAviso = new javax.swing.JList<>();
        btnCerrar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 576));
        setUndecorated(true);
        getContentPane().setLayout(null);

        btnFuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alarmAC.png"))); // NOI18N
        btnFuego.setBorderPainted(false);
        btnFuego.setContentAreaFilled(false);
        btnFuego.setFocusPainted(false);
        btnFuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFuego);
        btnFuego.setBounds(250, 10, 160, 80);

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 125));

        jScrollPane1.setViewportView(txtAviso);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(525, 510, 170, 50);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarC.png"))); // NOI18N
        btnCerrar.setPreferredSize(new java.awt.Dimension(34, 34));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(650, 10, 34, 34);
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 720, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuegoActionPerformed
        if(estadoF){
            
            icono="D:\\Tecno\\4to semestre\\prog\\unidad 3\\proyecto\\ProyectoHilos\\src\\gifs\\finfuego.gif";
            imagen= new ImageIcon(icono);
            Incendio.Fondo.setIcon(new ImageIcon(icono));
            estadoF=false;
            objIncendio.Alarma(estadoF);
        }else{
            
            estadoF=true;
            objIncendio.Alarma(estadoF);
        }
        
    }//GEN-LAST:event_btnFuegoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        VPrin ventana= new VPrin();
        hiloF.stop();
        ventana.show();
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            System.out.println("Entro al main");
            Thread hiloF= new Thread(objIncendio);
            hiloF.start();
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incendio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incendio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incendio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incendio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incendio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnFuego;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> txtAviso;
    // End of variables declaration//GEN-END:variables
}
